name: Depenendent Jobs Example

on: ['push']
jobs:
  my-dep-job2:
    
    runs-on: ubuntu-latest
    steps:
      - name: stepB
        run: echo "World"
  my-dep-job1:
    runs-on: ubuntu-latest
    steps:
      - name: stepA
        run: echo "Hello"



